<?php
/**
 * @file
 * Code for the pushtape_discography feature.
 */

include_once('pushtape_discography.features.inc');


/**
 * Implements hook_panelizer_default_types_alter()
 */
function pushtape_discography_panelizer_defaults_alter(&$defaults) {
  // Require the panels panelizer include from features since 
  // features doesn't support hook_panelizer_defaults() correctly.
  // See https://drupal.org/node/1427150 for more on that.
  require_once('pushtape_discography.panelizer.inc');
  foreach(pushtape_discography_panelizer_defaults() as $name => $default) {
    $defaults[$name] = $default;
  }
}

/**
 * Implementation of hook_apps_app_info()
 */
function pushtape_discography_apps_app_info() {
  return array(
    'demo content description' => 'add some tracks and terms',
    'demo content module' => 'pushtape_discography_democontent',
    'configure form' => 'pushtape_discography_configure_form',
    // 'post install callback' => 'pushtape_discography_app_post_install', // This will be called after the app is enabled intialy or of the app has been uninstalled
    // 'status callback' => 'pushtape_discography_app_status'
  );
}

/** 
 * App Configuration Form
 */
function pushtape_discography_configure_form($form, &$form_state) {
  $form = array();

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save'),
  );

   return $form;
}
